// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Sample

import "strconv"

type Equipment byte

const (
	EquipmentNONE   Equipment = 0
	EquipmentWeapon Equipment = 1
)

var EnumNamesEquipment = map[Equipment]string{
	EquipmentNONE:   "NONE",
	EquipmentWeapon: "Weapon",
}

var EnumValuesEquipment = map[string]Equipment{
	"NONE":   EquipmentNONE,
	"Weapon": EquipmentWeapon,
}

func (v Equipment) String() string {
	if s, ok := EnumNamesEquipment[v]; ok {
		return s
	}
	return "Equipment(" + strconv.FormatInt(int64(v), 10) + ")"
}
